### model
model_name_or_path: ./gemma-2b-it #google/gemma-2b-it
ref_model: ./gemma-2b-it #google/gemma-2b-it
ref_model_adapters: saves/gemma-2b/lora/ulfeedback_train40K_sft_fst/checkpoint-3535

### method
stage: taorm
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
deepspeed: examples/deepspeed/ds_z2_offload_config.json

### dataset
dataset: ulfeedback_train40K
template: gemma
cutoff_len: 1024
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
new_special_tokens: "[STEP],[REQ],[SPACE]"

### output
output_dir: saves/gemma-2b/lora/ulfeedback_train40K_reward_0001sft_01reg_mean_bt_ref_fst #_002_10reg_ra2
logging_steps: 2000
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 6
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
weight_ratio: 0.001
reg_ratio: 0.1
radis: 2.0 # 2:fst 1:sed
temp_ratio: 1.0
use_pref: true
use_log: true
use_align: true

### eval
eval_dataset: ulfeedback_eval40K
val_size: 0.0
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 2000
