### model
model_name_or_path: google/gemma-2b-it #meta-llama/Meta-Llama-3-8B-Instruct #

### method
stage: taorm_sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
deepspeed: examples/deepspeed/ds_z2_offload_config.json

### dataset
dataset: ulfeedback_train40K #ulfeedback_train40K
template: gemma 
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
new_special_tokens: "[STEP],[REQ],[SPACE]"

### output
output_dir: saves/gemma-2b/lora/ulfeedback_train40K_sft_fst #_002_10reg_ra2
logging_steps: 1000
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 6
learning_rate: 1.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
weight_ratio: 0.001
reg_ratio: 0.0
radis: 2.0 # 2:fst 1:sed
use_pref: true
use_log: true
use_align: true

### eval
eval_dataset: ulfeedback_eval40K
val_size: 0.0
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 1000

