### model
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
ref_model: Qwen/Qwen2.5-7B-Instruct

### method
stage: orm_dg
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
deepspeed: examples/deepspeed/ds_z2_offload_config.json

### dataset
dataset: qwen_train
template: qwen
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
new_special_tokens: "[STEP],[REQ],[SPACE]"

### output
output_dir: saves/gemma-2b/lora/qwen_reward_0001sft_bt_ref_fst #_002_10reg_ra2
logging_steps: 1000
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
weight_ratio: 0.001
reg_ratio: 0.1
radis: 2.0
use_pref: true
use_log: true
use_align: true

### eval
#eval_dataset: qwen_eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 1000

